org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true



extType=music
extId=fartnite
extClass=YoutubeExtension

extIconUrl=https://music.youtube.com/img/favicon_144.png
extName=Youtube Music
extDescription=Youtube Music Extension for Echo,with the help of YTM-kt library + NewPipeExtractor-KMP.

extAuthor=TAbhishekkumar6
extAuthorUrl=https://github.com/TAbhishekkumar6

extRepoUrl=https://github.com/thgillwtnorizoh/cisuM_ebutuoY-ocE
extUpdateUrl=https://api.github.com/repos/thgillwtnorizoh/cisuM_ebutuoY-ocE/releases
